#!/sbin/sh
#
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
#
# Copyright 2017 Nexenta Systems, Inc. All rights reserved.
#

#
# Name service switch script.
#

. /lib/svc/share/smf_include.sh
. /lib/svc/share/net_include.sh

NSS_FMRI="svc:/system/name-service-switch"
DEFAULT_NSS_CONFIG="/etc/nsswitch.dns"
NSS_CONFIG="/etc/nsswitch.conf"
CHMOD=/usr/bin/chmod
CP=/usr/bin/cp
GREP=/usr/bin/grep
NAWK=/usr/bin/nawk
SED=/usr/bin/sed
SVCCFG=/usr/sbin/svccfg

unconfigure()
{

	entries=$($NAWK -F: '/^[a-z]*:/ { print $1 }' $DEFAULT_NSS_CONFIG)
	for e in $entries; do
		name=`$GREP ^$e: $DEFAULT_NSS_CONFIG`
		name=${name##*:}
		$SVCCFG -s $NSS_FMRI setprop config/$e = astring: \"$name\"
	done

	$CP -f $DEFAULT_NSS_CONFIG $NSS_CONFIG
	if [ $? -ne 0 ]; then
		err=$?
		msg="Error copying $DEFAULT_NSS_CONFIG to $NSS_CONFIG"
		net_record_err "$msg" $err
		return $SMF_EXIT_ERR_FATAL
	fi

	$CHMOD 644 $NSS_CONFIG
	if [ $? -ne 0 ]; then
		err=$?
		msg="Error setting permissions on $NSS_CONFIG"
		net_record_err "$msg" $err
		return $SMF_EXIT_ERR_FATAL
	fi

	return $SMF_EXIT_OK
}

case "$1" in
'start'|'refresh')

	defval=$($SVCCFG -s $NSS_FMRI listprop config/default | \
		$NAWK '{ print $3 }')
	if [[ "$defval" == "true" ]]; then
		msg="Setting $NSS_CONFIG to default values"
		net_record_err "$msg" 0
		unconfigure
		if [ $? -ne 0 ]; then
			exit $SMF_EXIT_ERR_CONFIG 
		fi	
		exit $SMF_EXIT_OK	
	fi

	entries=$($NAWK -F: '/^[a-z]*:/ { print $1 }' $DEFAULT_NSS_CONFIG)
	for e in $entries; do
		propval=$($SVCCFG -s $NSS_FMRI listprop config/$e | \
			$NAWK -F\" '{ print $2 }')

		# Setting default values if SMF value is absent	
		if [[ -z "$propval" ]]; then
			propval="files"
			if [[ "$e" == "ipnodes" ]] || [[ "$e" == "hosts" ]]; then
				propval="files dns mdns"
			elif [[ "$e" == "printers" ]]; then
				propval="user files"
			fi	
		fi	

		$SED -i -e "s/^\($e:\s*\)\(.*\)/\1 $propval/g" $NSS_CONFIG
		if [ $? -ne 0 ]; then
			err=$?
			msg="Error setting \"$e\" entry"
			net_record_err "$msg" $err
			exit $SMF_EXIT_ERR_CONFIG
		fi
	done

	exit $SMF_EXIT_OK
	;; 
'unconfigure')
	unconfigure
	;;
*)
	echo "Usage: $0 { start | stop | refresh | unconfigure }"
	exit 1
	;;
esac
exit $SMF_EXIT_OK
